### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [DuncanRuns/RememberMyTxt#2]
Do you plan on updating?

**Comment by DuncanRuns** [comment]
You can try it with the existing one, might just work, if not I'll make a new update for it

**Comment by DuncanRuns** [comment]
I have tested and can confirm the 1.19 version of the mod works for 1.19.3
<https://modrinth.com/mod/remember-my-txt/version/v1.0.0+MC1.19>

**Comment by Aces-and-Jacks** [comment]
Ok. Haven't started using 1.19.3 yet since I'm still waiting on other mods to update but if it doesn't work I'll let you know. 
Edit: didn't see you've already tested so never mind
